# Generated by Django 3.2.8 on 2021-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField(blank=True, null=True)),
                ('father_name', models.TextField(blank=True, null=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('pin', models.TextField(blank=True, null=True)),
                ('phoneNo', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('class_opted', models.TextField(blank=True, null=True)),
                ('marks', models.TextField(blank=True, null=True)),
                ('date_enrolled', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
